# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_name', models.CharField(max_length=200)),
                ('sensor_data', models.CharField(max_length=200)),
                ('create_date', models.DateTimeField()),
            ],
        ),
    ]
